os:
 - osx
 - linux

language: go

go:
  - 1.9.x

if: tag =~ ^v

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - "./*.tar.gz"
    - "./*.dmg"
    - "./*.zip"
  skip_cleanup: true
  on:
    tags: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn ; fi # wine
  - go get -u github.com/golang/dep/cmd/dep
  - python before_install.py
  - cat $GOPATH/src/github.com/decred/decrediton/package.json
  - (cd $GOPATH/src/github.com/decred/dcrd && dep ensure -v)
  - (cd $GOPATH/src/github.com/decred/dcrwallet && dep ensure -v)
  - mkdir $GOPATH/src/github.com/decred/decrediton/bin
  - (cd $GOPATH/src/github.com/decred/decrediton/bin && go build -v github.com/decred/dcrd)
  - (cd $GOPATH/src/github.com/decred/decrediton/bin && go build -v github.com/decred/dcrd/cmd/dcrctl)
  - (cd $GOPATH/src/github.com/decred/decrediton/bin && go build -v github.com/decred/dcrwallet)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd $GOPATH/src/github.com/decred/decrediton && yarn && yarn package-dev-linux) ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (cd $GOPATH/src/github.com/decred/decrediton && yarn && yarn package) ; fi
  - cp $GOPATH/src/github.com/decred/decrediton/release/*.* $TRAVIS_BUILD_DIR
  - (cd $TRAVIS_BUILD_DIR && echo $PWD && ls)

script:
  - echo "hooray!"
