language: go

go:
  - 1.9.x

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - git clone https://github.com/decred/dcrd $GOPATH/src/github.com/decred/dcrd
  - git clone https://github.com/decred/dcrwallet $GOPATH/src/github.com/decred/dcrwallet
  - git clone https://github.com/decred/decrediton $GOPATH/src/github.com/decred/decrediton
  - python3 before_install.py
  - (cd $GOPATH/src/github.com/decred/dcrd && dep ensure -v)
  - (cd $GOPATH/src/github.com/decred/dcrwallet && dep ensure -v)
  - mkdir $GOPATH/src/github.com/decred/decrediton/bin
  - (cd $GOPATH/src/github.com/decred/decrediton/bin && go build -v github.com/decred/dcrd)
  - (cd $GOPATH/src/github.com/decred/decrediton/bin && go build -v github.com/decred/dcrd/cmd/dcrctl)
  - (cd $GOPATH/src/github.com/decred/decrediton/bin && go build -v github.com/decred/dcrwallet)
  - ls
  - ls $GOPATH/src/github.com/decred/decrediton/bin
  # - (cd $GOPATH/src/github.com/decred/decrediton && yarn && yarn package && ls release)


  # - go get -v github.com/decred/dcrd
  # - go get -v github.com/decred/dcrwallet
  # # - go get -v github.com/decred/decrediton
  # - cd $GOPATH/src/github.com/decred/dcrd && dep ensure && go install . cmd/...
  # - cd $GOPATH/src/github.com/decred/dcrwallet && dep ensure && go install . cmd/...

script:
  - echo "hooray!"
