os:
 - osx
 - linux

language: go

go:
  - 1.12.x

# if: tag =~ ^v

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - "./*.tar.gz"
    - "./*.dmg"
    - "./*.zip"
  skip_cleanup: true
  on:
    tags: true

before_install:
  - nvm install 10.13 && nvm use 10.13
  - nvm list
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn ; fi # wine
  - ROOT_BUILD="$TRAVIS_HOME" python before_install.py
  - cd $TRAVIS_HOME/src
  - ls
  - cat $HOME/src/decrediton/package.json
  - mkdir $HOME/src/decrediton/bin
  - (cd dcrd && go build -o ../decrediton/bin/dcrd -v .)
  - (cd dcrd && go build -o ../decrediton/bin/dcrctl -v ./cmd/dcrctl)
  - (cd dcrwallet && go build -o ../decrediton/bin/dcrwallet -v .)
  - cd $TRAVIS_BUILD_DIR
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd $HOME/src/decrediton && yarn && yarn package-dev-linux) ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (cd $HOME/src/decrediton && yarn && yarn package) ; fi
  - cp $HOME/src/decrediton/release/*.* $TRAVIS_BUILD_DIR
  - (echo "Contents of $PWD" && ls)

script:
  - echo "hooray!"
