language: go

go:
  - 1.9.x

# addons:
#   apt:
#     packages:
#       - wine

deploy:
  provider: releases
  api_key: "$GITHUB OAUTH TOKEN"
  file: *.tar.gz
  skip_cleanup: true

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - git clone https://github.com/$GITHUB_DECRED_OWNER/dcrd $GOPATH/src/github.com/decred/dcrd
  - git clone https://github.com/$GITHUB_DECRED_OWNER/dcrwallet $GOPATH/src/github.com/decred/dcrwallet
  - git clone https://github.com/$GITHUB_DECRED_OWNER/decrediton $GOPATH/src/github.com/decred/decrediton
  - python3 before_install.py
  - cat $GOPATH/src/github.com/decred/decrediton/package.json
  - (cd $GOPATH/src/github.com/decred/dcrd && dep ensure -v)
  - (cd $GOPATH/src/github.com/decred/dcrwallet && dep ensure -v)
  - mkdir $GOPATH/src/github.com/decred/decrediton/bin
  - (cd $GOPATH/src/github.com/decred/decrediton/bin && go build -v github.com/decred/dcrd)
  - (cd $GOPATH/src/github.com/decred/decrediton/bin && go build -v github.com/decred/dcrd/cmd/dcrctl)
  - (cd $GOPATH/src/github.com/decred/decrediton/bin && go build -v github.com/decred/dcrwallet)
  - (cd $GOPATH/src/github.com/decred/decrediton && yarn && yarn package-dev-linux)
  - ls $GOPATH/src/github.com/decred/decrediton/release
  - cp $GOPATH/src/github.com/decred/decrediton/release/*.tar.gz $TRAVIS_BUILD_DIR


  # - go get -v github.com/decred/dcrd
  # - go get -v github.com/decred/dcrwallet
  # # - go get -v github.com/decred/decrediton
  # - cd $GOPATH/src/github.com/decred/dcrd && dep ensure && go install . cmd/...
  # - cd $GOPATH/src/github.com/decred/dcrwallet && dep ensure && go install . cmd/...

script:
  - echo "hooray!"
