os:
 - osx
 - linux

language: go

go:
  - 1.11.x

# if: tag =~ ^v

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - "./*.tar.gz"
    - "./*.dmg"
    - "./*.zip"
  skip_cleanup: true
  on:
    tags: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn ; fi # wine
  - export ROOT_BUILD="$TRAVIS_BUILD_DIR"
  - python before_install.py
  - cat $HOME/src/decrediton/package.json
  - mkdir $HOME/src/decrediton/bin
  - (cd $HOME/src/decrediton/bin && go build -v github.com/decred/dcrd)
  - (cd $HOME/src/decrediton/bin && go build -v github.com/decred/dcrd/cmd/dcrctl)
  - (cd $HOME/src/decrediton/bin && go build -v github.com/decred/dcrwallet)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd $HOME/src/decrediton && yarn && yarn package-dev-linux) ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (cd $HOME/src/decrediton && yarn && yarn package) ; fi
  - cp $HOME/src/decrediton/release/*.* $TRAVIS_BUILD_DIR
  - (cd $TRAVIS_BUILD_DIR && echo $PWD && ls)

script:
  - echo "hooray!"
